---
title: "C++ Course Lecture 1"
author: "dfbakin"
date: "2024"
theme: metropolis
transition: slide
format: 
    beamer:
        pdf-engine: xelatex
        aspectratio: 169
        fontsize: 9pt
        section-titles: true
        incremental: true
        include-in-header: ../../files/presentation_header.tex
header-includes:
 - \newcommand{\bgimage}{../files/back13.jpeg}
---

# Немного о языке

На этом курсе будет рассматриваться язык C++, который был создан в 1980-х как расширение языка C, в котором не было доступно ООП (объектно-ориентированное программирование).  
Автор C++ — [Бьёрн Страуструп](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%83%D1%81%D1%82%D1%80%D1%83%D0%BF,_%D0%91%D1%8C%D1%91%D1%80%D0%BD).

---

## Особенности языка

Этот язык является:

- **Компилируемым** — по тексту программы создается исполняемый файл, который затем можно запустить.
- **Статически типизируемым** — у каждой переменной есть свой тип, который определен еще в коде до компиляции.
- **Универсальным** по сфере применения.
- **Инструментом** для прямого управления памятью.

---

# Hello, world!

```cpp
#include <iostream>

int main() {
    std::cout << "Hello, world!\n";
}
```

В примере выше мы подключаем нужный модуль директивой `#include`, затем в функции `main` отправляем строку в поток вывода.

---

# Переменные

Переменная — объект определенного типа, у нее может быть определено значение.  
Тип переменной должен быть известен на этапе компиляции.

```cpp
#include <iostream>

int main() {
    int number = 0;
    std::cout << "Our number is " << number << std::endl;
}
```

---

## Типы переменных

[Полный список встроенных типов](https://en.cppreference.com/w/cpp/language/types)

```cpp
char c = '1';                // символ
std::string s = "text";      // строка
bool b = true;               // булевая переменная
int i = 42;                  // целое число
float f = 2.71828;           // дробное число
double d = 3.141592;         // число двойной точности
```

---

# Ввод-вывод

```cpp
#include <iostream>
#include <string>

int main() {
    std::string name;
    std::cout << "What is your name?\n";
    std::cin >> name;
    std::cout << "Hello, " << name << "!\n";
}
```

---

# Арифметические операции

```cpp
int main() {
    int a = 7, b = 3;
    int q = a / b;  // 2
    int r = a % b;  // 1
}
```

---

# Задача о нахождении гипотенузы

Дано два числа `a` и `b`. Найдите гипотенузу треугольника с заданными катетами.

```cpp
#include <iostream>
#include <cmath>

int main() {
    int a, b;
    std::cin >> a >> b;
    float hypot = std::sqrt(a * a + b * b);
    std::cout << hypot << '\n';
}
```

---

# Задача о разрядах числа

```cpp
#include <iostream>

int main() {
    int num = 12345;
    std::cout << num % 10 << '\n'; // 5
    std::cout << num / 10 % 10 << '\n'; // 4
    std::cout << num / 100 % 10 << '\n'; // 3
}
```

---

# Представление чисел в памяти

## Два-дополнительный код

| Биты | Число |
|------|-------|
| 0    | 0     |
| 1    | 1     |
| 10   | 2     |
| 11   | 3     |
| 100  | -4    |
| 101  | -3    |
| 110  | -2    |
| 111  | -1    |

---

# Спасибо за внимание!
