project:
  type: website
  output-dir: _site

# Meta
description-meta: "Intoduction to C++ for HSE Lyceum (2024)"
author-meta: "Denis Bakin"

website:
  title: "C++ Course"
  # image: "https://quarto.org/quarto.png"
  description: "Website of 'Intoduction to C++' for HSE Lyceum (2024)"

  navbar:
    background: dark

    left:
      - text: Описание курса
        href: index.qmd
      # - text: Расписание
      #   href: main_pages/schedule.qmd
      - text: Материалы лекций
        href: main_pages/lectures.qmd
      - text: Lyceum DMOJ (placeholder)
        href: https://google.com
        target: _blank
      - text: Contact me (TODO)
        href: https://dfbakin.com/contacts
      - text: Guides (TODO)
        href: https://google.com

      # - text: About
      #   menu:
      #     - text: News
      #       href: posts.qmd#category=news
      #     - text: Events
      #       href: posts.qmd#category=event
      #     - text: Contact
      #       href: contact.qmd

    right:
      - icon: code-square
        href: https://google.com
        target: _blank
      - icon: person-circle
        href: https://dfbakin.com
        target: _blank
      - icon: github
        href: https://github.com/dfbakin/cpp-course-2024
        target: _blank

  page-navigation: true

  page-footer:
    left: "[Denis Bakin](https://github.com/dfbakin/) &copy; <script>document.write(new Date().getFullYear())</script>"
    center: >
      Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template)
      adapted by [Dr. Gang He](http://drganghe.github.io)
    right:
      - icon: github
        href: https://github.com/dfbakin/cpp-course-2024
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true

  draft-mode: unlinked

  repo-url: https://github.com/dfbakin/cpp-course-2024
#  repo-actions: [edit, issue, source]

  open-graph: true

  twitter-card: true
#  card-style: summary

  site-url: "https://cpp24.dfbakin.com"

  # google-analytics:
  #   tracking-id: ""  # Please delete or replace with your own tracking ID
  #   anonymize-ip: true

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    # link-external-filter: "^(?:http:|https:)\/\/drganghe\.github\.io\/custom"
